twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        catalogItemClass: 'SiteBundle\Entity\Pages\CatalogItem'
        catalogArticleClass: 'SiteBundle\Entity\Pages\CatalogArticle'
        portfolioItemClass: 'SiteBundle\Entity\Pages\PortfolioItemPage'
        interiorItemClass: 'SiteBundle\Entity\Pages\InteriorItemPage'
    form_themes:
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - 'ZemaJsontableBundle:Form:jsontable_widget.html.twig'
