# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
    branches:
        master:
            - step:
                script:
                    - mkdir -p ~/.ssh
                    - cat ./deploy/my_known_hosts >> ~/.ssh/known_hosts
                    - touch ~/.ssh/id_rsa
                    - touch ~/.ssh/id_rsa.pub
                    - (umask  077 ; cat ./deploy/id_rsa  > ~/.ssh/id_rsa)
                    - (cat ./deploy/id_rsa.pub  > ~/.ssh/id_rsa.pub)
                    - chmod 400 ~/.ssh/id_rsa
                    - ssh $VDS_USER@$VDS_HOST 'cd /home/u28464/fire96.mylikbez.ru  && timeout 59s git pull origin master  && /bin/bash  deploy-vds.sh'
