site_bundle:
    resource: "@SiteBundle/Resources/config/routes.yaml"
    prefix:   /

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

zema_tree:
    resource: "@ZemaTreeBundle/Resources/config/routing.yml"
    prefix:   /admin


comur_image:
  resource: "@ComurImageBundle/Resources/config/routing.yml"
  prefix:   /

app_main.error:
  path:  /{path}
  controller: App\Controller\RedirectController::pageNotFound
  requirements:
          path: .*
