<?php

namespace SiteBundle\Repository;

/**
 * SiteTextsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTextsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Массив код-значение
     * @return array [code => value]
     */
    public function getList()
    {
        $objs = $this->findAll();
        $res = [];
        foreach ($objs as $obj) {
            $res[$obj->getAlias()] = $obj->getValue();
        }
        return $res;
    }
}
